# This file was generated by formula-gen.
# See: https://github.com/grafana/alloy/blob/main/packaging/homebrew/formula-gen/README.md
class Alloy < Formula
  desc "Vendor-agnostic OpenTelemetry Collector distribution with programmable pipelines"
  homepage "https://grafana.com/docs/alloy/latest"
  # Explicit version: the release zips carry no version in their filename, and
  # Homebrew would otherwise misparse it (e.g. "64" from "amd64").
  version "1.17.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grafana/alloy/releases/download/v1.17.0/alloy-darwin-arm64.zip"
      sha256 "3418ec143c452347307e56ca75ba880f418cec9b51e7aec554c22b4a198ed5a3"
    end
    if Hardware::CPU.intel?
      url "https://github.com/grafana/alloy/releases/download/v1.17.0/alloy-darwin-amd64.zip"
      sha256 "8321c4cd99d6aec8e49c425e5a7e43b695f2c54a37687a3c8238558b2b33f8f7"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grafana/alloy/releases/download/v1.17.0/alloy-linux-amd64.zip"
      sha256 "a905f3c750855323e12b23630150972956e24c993f0c9170ca2f0af4bd442d8e"
    end

    if Hardware::CPU.arm?
      url "https://github.com/grafana/alloy/releases/download/v1.17.0/alloy-linux-arm64.zip"
      sha256 "169f2b3b0f0bff30b9fd7b8c924b950c4aa910e20f39979abbb510f1c3e9daf7"
    end
  end

  # Extra install steps from alloy.rb.original. Compilation steps removed.
  def install
    # The release zip contains a single binary named alloy-<os>-<arch>, which
    # Homebrew auto-extracts. Its executable bit is not preserved in the zip, so
    # restore it after install.
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "alloy-#{os}-#{arch}" => "alloy"
    (bin/"alloy").chmod 0755

    generate_completions_from_executable(bin/"alloy", shell_parameter_format: :cobra)

    # Create a config.alloy file with default Alloy configuration
    (buildpath/"config.alloy").write <<~EOS
      logging {
        level  = "info"
        format = "logfmt"
      }
    EOS

    pkgetc.install "config.alloy"

    # Create an empty config.env file for environment variables
    (buildpath/"config.env").write ""
    pkgetc.install "config.env"

    # Create an empty extra-args.txt file for extra command line arguments
    (buildpath/"extra-args.txt").write ""
    pkgetc.install "extra-args.txt"

    # Create a wrapper script to run Alloy using the config in config.alloy,
    # env vars in config.env, and extra args in extra-args.txt
    (buildpath/"alloy-wrapper").write <<~SH
      #!/usr/bin/env sh
      if [ -f "#{pkgetc}/config.env" ]; then
        set -a
        . "#{pkgetc}/config.env"
        set +a
      fi

      otel_mode=""
      case "${ALLOY_OTEL_MODE:-}" in
        1 | true | yes | on ) otel_mode="1" ;;
      esac

      extra_args_file="#{pkgetc}/extra-args.txt"
      [ -n "$otel_mode" ] && extra_args_file="#{pkgetc}/otel-extra-args.txt"

      extra_args=""
      [ -f "$extra_args_file" ] && extra_args=$(cat "$extra_args_file")

      # extra_args is intentionally unquoted so a file with multiple arguments
      # word-splits into separate argv entries.
      if [ -n "$otel_mode" ]; then
        exec "#{opt_bin}/alloy" otel \
          --config="file:#{pkgetc}/config.yaml" \
          $extra_args
      else
        exec "#{opt_bin}/alloy" run \
          --storage.path="#{var}/lib/alloy/data" \
          $extra_args \
          "#{pkgetc}"
      fi
    SH

    bin.install "alloy-wrapper"
    mkdir_p (var/"lib/alloy/data")
  end

  def caveats
    <<~EOS
      Alloy uses a set of files that you can customize before running:
        Configuration:
          #{pkgetc}/config.alloy
        Environment variables:
          #{pkgetc}/config.env
        Extra command line arguments:
          #{pkgetc}/extra-args.txt

      To enable the OTel Engine:
        - Set "ALLOY_OTEL_MODE=1" in #{pkgetc}/config.env
        - Create collector config in #{pkgetc}/config.yaml
        - If necessary, create #{pkgetc}/otel-extra-args.txt to add command line arguments.
    EOS
  end

  service do
    run ["#{opt_bin}/alloy-wrapper"]
    keep_alive true
    log_path var/"log/alloy.log"
    error_log_path var/"log/alloy.err.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/alloy --version")

    port = free_port

    (testpath/"config.alloy").write <<~EOS
      logging {
        level = "info"
      }
    EOS

    fork do
      exec bin/"alloy", "run", "#{testpath}/config.alloy",
        "--server.http.listen-addr=127.0.0.1:#{port}",
        "--storage.path=#{testpath}/data"
    end
    sleep 10

    output = shell_output("curl -s 127.0.0.1:#{port}/metrics")
    assert_match "alloy_build_info", output
  end
end
