# This file was generated by formula-gen.
# See: https://github.com/grafana/alloy/blob/main/packaging/homebrew/formula-gen/README.md
class Alloy < Formula
  desc "Vendor-agnostic OpenTelemetry Collector distribution with programmable pipelines"
  homepage "https://grafana.com/docs/alloy/latest"
  version "1.18.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grafana/alloy/releases/download/v1.18.1/alloy-darwin-arm64.zip"
      sha256 "29bb1342eb2313a1bfeb486aeea25583d828da34b60d29c8583fc6a99544e3c2"
    end
    if Hardware::CPU.intel?
      url "https://github.com/grafana/alloy/releases/download/v1.18.1/alloy-darwin-amd64.zip"
      sha256 "7baf34a99554c252c463c348d9a46ed66a7cd54111569119087b224b012ea541"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grafana/alloy/releases/download/v1.18.1/alloy-linux-amd64.zip"
      sha256 "fac853cbc3983a50a2368f9a685b31f74392ae86dd6155461b11a911c07b483c"
    end

    if Hardware::CPU.arm?
      url "https://github.com/grafana/alloy/releases/download/v1.18.1/alloy-linux-arm64.zip"
      sha256 "499446cfe22514d6c9f00af953d98162526ea818e84c4e452f8fddbbfa8676d6"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "alloy-#{os}-#{arch}" => "alloy"
    (bin/"alloy").chmod 0755

    generate_completions_from_executable(bin/"alloy", shell_parameter_format: :cobra)

    # Create a config.alloy file with default Alloy configuration
    (buildpath/"config.alloy").write <<~EOS
      logging {
        level  = "info"
        format = "logfmt"
      }
    EOS

    pkgetc.install "config.alloy"

    # Create an empty config.env file for environment variables
    (buildpath/"config.env").write ""
    pkgetc.install "config.env"

    # Create an empty extra-args.txt file for extra command line arguments
    (buildpath/"extra-args.txt").write ""
    pkgetc.install "extra-args.txt"

    # Create a wrapper script to run Alloy using the config in config.alloy,
    # env vars in config.env, and extra args in extra-args.txt
    (buildpath/"alloy-wrapper").write <<~SH
      #!/usr/bin/env sh
      if [ -f "#{pkgetc}/config.env" ]; then
        set -a
        . "#{pkgetc}/config.env"
        set +a
      fi

      otel_mode=""
      case "${ALLOY_OTEL_MODE:-}" in
        1 | true | yes | on ) otel_mode="1" ;;
      esac

      extra_args_file="#{pkgetc}/extra-args.txt"
      [ -n "$otel_mode" ] && extra_args_file="#{pkgetc}/otel-extra-args.txt"

      extra_args=""
      [ -f "$extra_args_file" ] && extra_args=$(cat "$extra_args_file")

      # extra_args is intentionally unquoted so a file with multiple arguments
      # word-splits into separate argv entries.
      if [ -n "$otel_mode" ]; then
        exec "#{opt_bin}/alloy" otel \
          --config="file:#{pkgetc}/config.yaml" \
          $extra_args
      else
        exec "#{opt_bin}/alloy" run \
          --storage.path="#{var}/lib/alloy/data" \
          $extra_args \
          "#{pkgetc}"
      fi
    SH

    bin.install "alloy-wrapper"
    mkdir_p (var/"lib/alloy/data")
  end

  def caveats
    <<~EOS
      Alloy uses a set of files that you can customize before running:
        Configuration:
          #{pkgetc}/config.alloy
        Environment variables:
          #{pkgetc}/config.env
        Extra command line arguments:
          #{pkgetc}/extra-args.txt

      To enable the OTel Engine:
        - Set "ALLOY_OTEL_MODE=1" in #{pkgetc}/config.env
        - Create collector config in #{pkgetc}/config.yaml
        - If necessary, create #{pkgetc}/otel-extra-args.txt to add command line arguments.
    EOS
  end

  service do
    run ["#{opt_bin}/alloy-wrapper"]
    keep_alive true
    log_path var/"log/alloy.log"
    error_log_path var/"log/alloy.err.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/alloy --version")

    port = free_port

    (testpath/"config.alloy").write <<~EOS
      logging {
        level = "info"
      }
    EOS

    fork do
      exec bin/"alloy", "run", "#{testpath}/config.alloy",
        "--server.http.listen-addr=127.0.0.1:#{port}",
        "--storage.path=#{testpath}/data"
    end
    sleep 10

    output = shell_output("curl -s 127.0.0.1:#{port}/metrics")
    assert_match "alloy_build_info", output
  end
end
