# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cortextool < Formula
  desc "Tools for interacting with Cortex"
  homepage "https://grafana.com"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grafana/cortex-tools/releases/download/v0.11.0/cortextool_0.11.0_darwin_arm64.tar.gz"
      sha256 "b056092d1309c18867f9390b3d6e75a3bcbb3973ab9c212dbcd957136c974c03"

      def install
        bin.install "cortextool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grafana/cortex-tools/releases/download/v0.11.0/cortextool_0.11.0_darwin_amd64.tar.gz"
      sha256 "cf6d1592a9ec27a1d96bba49b8c6dd89cedc0b18739ee0d9f50eeaf281fa8f88"

      def install
        bin.install "cortextool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grafana/cortex-tools/releases/download/v0.11.0/cortextool_0.11.0_linux_amd64.tar.gz"
      sha256 "f66b710d33cc3bef8fd5dd31c96fbc992224123eab3e320cb1ae69cd4bd9cbf7"

      def install
        bin.install "cortextool"
      end
    end
  end
end
