# This file was generated by GoReleaser. DO NOT EDIT.
class Cortextool < Formula
  desc "Tools for interacting with Cortex"
  homepage "https://grafana.com"
  version "0.4.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/grafana/cortex-tools/releases/download/v0.4.2/cortextool_0.4.2_darwin_amd64.tar.gz"
    sha256 "d85f4d3bf8d1d108ebde3162fec71f76db0a50a1d32d92ce81d9b1389a7e791d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/grafana/cortex-tools/releases/download/v0.4.2/cortextool_0.4.2_linux_amd64.tar.gz"
      sha256 "1003e840b8e3efbece3905a61625ae51ecbc110dfd5ba1f2601c7c12c92b554e"
    end
  end

  def install
    bin.install "cortextool"
  end
end
