# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpK6 < Formula
  desc "An experimental MCP (Model Context Protocol) server for k6"
  homepage "https://github.com/grafana/mcp-k6"
  version "0.2.0"
  license "AGPL-3.0"

  depends_on "k6"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/grafana/mcp-k6/releases/download/v0.2.0/mcp-k6_0.2.0_darwin_amd64.tar.gz"
    sha256 "d2dc1848fc4b598bb81006b58a7830dfac181d73f14dd16554347e2d4a429407"

    def install
      bin.install "mcp-k6"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/grafana/mcp-k6/releases/download/v0.2.0/mcp-k6_0.2.0_darwin_arm64.tar.gz"
    sha256 "06d3d9e4964245d1c4e5cb3c8f8a75ae4263cc4d87922c1fac3cdab9c2377b73"

    def install
      bin.install "mcp-k6"
    end
  end

  test do
    system "#{bin}/mcp-k6", "--version"
  end
end
