# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mimirtool < Formula
  desc "Tools for interacting with Mimir"
  homepage "https://grafana.com"
  version "2.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/grafana/mimir/releases/download/mimir-2.1.0/mimir-darwin-arm64"
      sha256 "d08172197f748430eb9cb093cb493280fa60d655eed2784e2efe828ef37974d5"

      def install
        bin.install "mimirtool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/grafana/mimir/releases/download/mimir-2.1.0/mimir-darwin-amd64"
      sha256 "18e863c278e68bfc379b2c492f70a451f1af00a6a2d821e8134ecc119e639c9b"

      def install
        bin.install "mimirtool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/grafana/mimir/releases/download/mimir-2.1.0/mimirtool-linux-amd64"
      sha256 "44cd587702e017e6f2592dc5a77b3a8255122d0b46a01cb445db7074d59568a7"

      def install
        bin.install "mimirtool"
      end
    end
  end
end
