# This file was generated by GoReleaser. DO NOT EDIT.
cask "grafana-assistant" do
  name "grafana-assistant"
  desc "AI assistant for Grafana Cloud"
  homepage "https://github.com/grafana/assistant-cli"
  version "0.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grafana-assistant"

  on_macos do
    on_intel do
      url "https://github.com/grafana/assistant-cli/releases/download/v#{version}/grafana-assistant_#{version}_darwin_amd64.tar.gz"
      sha256 "72be33f2ba0c03076379ffdd47e5aa47f5d29b1a6a6eb0a693b4f14a4af1fb9f"
    end
    on_arm do
      url "https://github.com/grafana/assistant-cli/releases/download/v#{version}/grafana-assistant_#{version}_darwin_arm64.tar.gz"
      sha256 "541c8678b6856785e4689485c9fc3816b67184dd36cf7d191825a5bbbe34fbc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/grafana/assistant-cli/releases/download/v#{version}/grafana-assistant_#{version}_linux_amd64.tar.gz"
      sha256 "bf96746782b779f2fb1863011abdf71bacaee9442548739cd2ffbf10f3da18fc"
    end
    on_arm do
      url "https://github.com/grafana/assistant-cli/releases/download/v#{version}/grafana-assistant_#{version}_linux_arm64.tar.gz"
      sha256 "99cf27f069da9db37608cf86da4467ccf33ba950ee02da1562948489bc235fa9"
    end
  end

  # No zap stanza required
end
